/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./../src/pages/__root";
import { Route as R403Import } from "./../src/pages/403";
import { Route as IndexImport } from "./../src/pages/index";

// Create/Update Routes

const R403Route = R403Import.update({
  id: "/403",
  path: "/403",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/403": {
      id: "/403";
      path: "/403";
      fullPath: "/403";
      preLoaderRoute: typeof R403Import;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/403": typeof R403Route;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/403": typeof R403Route;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/403": typeof R403Route;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/403";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/403";
  id: "__root__" | "/" | "/403";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  R403Route: typeof R403Route;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/403"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/403": {
      "filePath": "403.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
